if(NOT DEFINED NODE_PLATFORM)
  if(CMAKE_SYSTEM_NAME STREQUAL "AIX")
    set(NODE_PLATFORM aix)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(NODE_PLATFORM mac)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "DragonFly")
    set(NODE_PLATFORM dragonflybsd)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    set(NODE_PLATFORM freebsd)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(NODE_PLATFORM linux)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "NetBSD")
    set(NODE_PLATFORM netbsd)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
    set(NODE_PLATFORM openbsd)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(NODE_PLATFORM win32)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Solaris|SunOS")
    set(NODE_PLATFORM sunos)
  endif()
endif()

# CMAKE_SYSTEM_PROCESSOR is always i386 on MacOS.  Since we only support
# 64 bits builds anyway, default to x64.
if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" OR
   CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64" OR
   CMAKE_SYSTEM_PROCESSOR STREQUAL "IA64" OR
   CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64" OR
   CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
  set(NODE_ARCH x64)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "i386" OR
       CMAKE_SYSTEM_PROCESSOR STREQUAL "i686" OR
       CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
  set(NODE_ARCH ia32)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm")
  set(NODE_ARCH arm)
elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ppc64")
  set(NODE_ARCH ppc64)
endif()

set(${NODE_PLATFORM} ON)
set(${NODE_ARCH} ON)
